name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            talk:
                - django-perf-and-you

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: cd ${{ matrix.talk }} && pnpm install

      - name: Install slidev
        run:  pnpm i -g @slidev/cli

      - name: Build
        run: cd ${{ matrix.talk }} && slidev build --base talks/${{ matrix.talk }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ matrix.talk }}/dist/
          destination_dir: ${{ matrix.talk }}
